development:
  adapter: sqlite3
  database: screens_development

test:
  adapter: sqlite3
  database: screens_test

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: screens_production
  pool: 5
  username: root
  password:
  socket: <%=
       ['/opt/local/var/run/mysql55/mysqld.sock', # macports 5.5
        '/opt/local/var/run/mysql5/mysqld.sock',  # macports 5.1
        '/opt/local/var/run/mysqld/mysqld.sock',  # macports again
        '/var/run/mysqld/mysqld.sock',            # ubuntu/debian
        '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>

