---
:package_name: airplay_wall
:package_dir: airplay_wall
:maintainer: BrightRoll Engineering - Aaron Stone
:email: aaron@brightroll.com
:userid: 3004
:groupid: 3004
:includes:
- README
- Rakefile
- Gemfile
- app
- bin
- db
- lib
- log
- config
- config.ru
- public
- script
- vendor/assets
- vendor/bundle
